# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pinger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pinger.proto", :syntax => :proto3) do
    add_message "pinger.Reqest" do
      optional :text, :string, 1
    end
    add_message "pinger.Response" do
      optional :text, :string, 1
      optional :count, :int32, 2
    end
  end
end

module Pinger
  Reqest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pinger.Reqest").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pinger.Response").msgclass
end
